### PR TITLE
Update afk.py

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Mhdrzn** [comment]
Wrong

**Comment by Mhdrzn** [comment]
No need **reason = None ** after else
Using f"string"

**Comment by ghost** [comment]
> No need **reason = None** after else
> 
> **Use f-string** _await message.edit(f"I'm on a misson {reason}")

My mistake fogot to add fstring 👀

**Review by Vaishnavofficial — COMMENTED** [review]
<b>There is no fixes here.</b> You are creating more issues.

**Pull request closed without merging**
